import { db } from "./db";
import { vipPackages, videos } from "@shared/schema";
import { sql } from "drizzle-orm";

export async function seedDatabase() {
  await db.execute(sql`DELETE FROM ${vipPackages}`);
  await db.insert(vipPackages).values([
    {
      name: "Stajyor",
      price: "0",
      dailyTasks: 3,
      perVideoReward: "0.31",
      dailyEarning: "0.95",
      level: 0,
      durationDays: 3,
      isLocked: false,
      emoji: "\u{1F193}",
      description: "Boshlang'ich sinov davri",
    },
    {
      name: "M1",
      price: "27",
      dailyTasks: 5,
      perVideoReward: "0.20",
      dailyEarning: "1.00",
      level: 1,
      durationDays: 60,
      isLocked: false,
      emoji: "\u{1F949}",
      description: "Kuniga 5 ta video vazifa",
    },
    {
      name: "M2",
      price: "63",
      dailyTasks: 6,
      perVideoReward: "0.42",
      dailyEarning: "2.50",
      level: 2,
      durationDays: 60,
      isLocked: false,
      emoji: "\u{1F948}",
      description: "Kuniga 6 ta video vazifa",
    },
    {
      name: "M3",
      price: "147",
      dailyTasks: 10,
      perVideoReward: "0.60",
      dailyEarning: "6.00",
      level: 3,
      durationDays: 60,
      isLocked: false,
      emoji: "\u{1F947}",
      description: "Kuniga 10 ta video vazifa",
    },
    {
      name: "M4",
      price: "343",
      dailyTasks: 14,
      perVideoReward: "1.05",
      dailyEarning: "14.70",
      level: 4,
      durationDays: 60,
      isLocked: true,
      emoji: "\u{1F512}",
      description: "Kuniga 14 ta video vazifa",
    },
    {
      name: "M5",
      price: "800",
      dailyTasks: 18,
      perVideoReward: "2.00",
      dailyEarning: "36.00",
      level: 5,
      durationDays: 60,
      isLocked: true,
      emoji: "\u{1F512}",
      description: "Kuniga 18 ta video vazifa",
    },
    {
      name: "M6",
      price: "1860",
      dailyTasks: 20,
      perVideoReward: "4.30",
      dailyEarning: "86.00",
      level: 6,
      durationDays: 60,
      isLocked: true,
      emoji: "\u{1F512}",
      description: "Kuniga 20 ta video vazifa",
    },
    {
      name: "M7",
      price: "4350",
      dailyTasks: 25,
      perVideoReward: "8.20",
      dailyEarning: "205.00",
      level: 7,
      durationDays: 60,
      isLocked: true,
      emoji: "\u{1F512}",
      description: "Kuniga 25 ta video vazifa",
    },
    {
      name: "M8",
      price: "10150",
      dailyTasks: 30,
      perVideoReward: "16.00",
      dailyEarning: "480.00",
      level: 8,
      durationDays: 60,
      isLocked: true,
      emoji: "\u{1F512}",
      description: "Kuniga 30 ta video vazifa",
    },
    {
      name: "M9",
      price: "23500",
      dailyTasks: 40,
      perVideoReward: "28.00",
      dailyEarning: "1120.00",
      level: 9,
      durationDays: 60,
      isLocked: true,
      emoji: "\u{1F512}",
      description: "Kuniga 40 ta video vazifa",
    },
    {
      name: "M10",
      price: "55000",
      dailyTasks: 50,
      perVideoReward: "53.00",
      dailyEarning: "2650.00",
      level: 10,
      durationDays: 60,
      isLocked: true,
      emoji: "\u{1F451}",
      description: "Kuniga 50 ta video vazifa",
    },
  ]);
  console.log("VIP packages seeded (11 tiers)");

  await db.execute(sql`DELETE FROM ${videos}`);
  {
    await db.insert(videos).values([
      {
        title: "Squid Game: Season 2",
        thumbnail: "https://image.tmdb.org/t/p/w500/bQXAqRx2Fgc46uCVWgoPz2bOeby.jpg",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        actors: "Lee Jung-jae, Wi Ha-jun, Gong Yoo",
        rating: "4.9",
        releaseDate: "2025-12-26",
        country: "Janubiy Koreya",
        duration: 25,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "The Last of Us: Season 2",
        thumbnail: "https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        actors: "Pedro Pascal, Bella Ramsey",
        rating: "4.8",
        releaseDate: "2026-04-13",
        country: "AQSH",
        duration: 22,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "Wednesday: Season 2",
        thumbnail: "https://image.tmdb.org/t/p/w500/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
        actors: "Jenna Ortega, Catherine Zeta-Jones",
        rating: "4.7",
        releaseDate: "2026-08-06",
        country: "AQSH",
        duration: 28,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "Thunderbolts*",
        thumbnail: "https://image.tmdb.org/t/p/w500/m0lqSkZFCnCIxHhlOGmvQiH5gIo.jpg",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
        actors: "Florence Pugh, Sebastian Stan",
        rating: "4.6",
        releaseDate: "2025-05-02",
        country: "AQSH",
        duration: 24,
        reward: "0",
        category: "Treyler",
      },
      {
        title: "Mission Impossible 8",
        thumbnail: "https://image.tmdb.org/t/p/w500/z1p34vh7dEOnLDaSZpNtfmUmjS0.jpg",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
        actors: "Tom Cruise, Hayley Atwell",
        rating: "4.9",
        releaseDate: "2025-05-23",
        country: "AQSH",
        duration: 26,
        reward: "0",
        category: "Treyler",
      },
      {
        title: "Stranger Things: Final Season",
        thumbnail: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
        actors: "Millie Bobby Brown, Finn Wolfhard",
        rating: "4.8",
        releaseDate: "2025-11-27",
        country: "AQSH",
        duration: 30,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "Supergirl: Woman of Tomorrow",
        thumbnail: "https://image.tmdb.org/t/p/w500/q1GmrEHDVEhPCvm1k7bEkScwETm.jpg",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
        actors: "Milly Alcock, Eve Ridley",
        rating: "4.5",
        releaseDate: "2026-06-26",
        country: "AQSH",
        duration: 22,
        reward: "0",
        category: "Treyler",
      },
      {
        title: "House of the Dragon: Season 3",
        thumbnail: "https://image.tmdb.org/t/p/w500/628Dep6AxEtDxjZoGP78TsOxYbK.jpg",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
        actors: "Matt Smith, Emma D'Arcy",
        rating: "4.7",
        releaseDate: "2026-06-15",
        country: "AQSH",
        duration: 25,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "Money Heist: Berlin",
        thumbnail: "https://image.tmdb.org/t/p/w500/jnE1GA0hlOOz0iJVkjCBhFNbMijt.jpg",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
        actors: "Pedro Alonso, Michelle Jenner",
        rating: "4.3",
        releaseDate: "2025-12-08",
        country: "Ispaniya",
        duration: 20,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "Avatar 3: Fire and Ash",
        thumbnail: "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
        actors: "Sam Worthington, Zoe Saldana",
        rating: "4.8",
        releaseDate: "2025-12-19",
        country: "AQSH",
        duration: 28,
        reward: "0",
        category: "Treyler",
      },
      {
        title: "Peaky Blinders: The Movie",
        thumbnail: "https://image.tmdb.org/t/p/w500/t5GEa9wSM7gp5DhRiMnPF5KuVjN.jpg",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
        actors: "Cillian Murphy, Tom Hardy",
        rating: "4.6",
        releaseDate: "2026-09-12",
        country: "Buyuk Britaniya",
        duration: 24,
        reward: "0",
        category: "Treyler",
      },
      {
        title: "The White Lotus: Season 3",
        thumbnail: "https://image.tmdb.org/t/p/w500/jOFnq2EGKb1hYnNfBuQRn3kO6Bi.jpg",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
        actors: "Walton Goggins, Patrick Schwarzenegger",
        rating: "4.4",
        releaseDate: "2025-02-16",
        country: "AQSH",
        duration: 20,
        reward: "0",
        category: "Tele-shou",
      },
    ]);
    console.log("Videos seeded (12 TV shows & trailers)");
  }

}
