import { db } from "./db";
import { vipPackages, videos, fundPlans } from "@shared/schema";
import { sql, eq } from "drizzle-orm";

export async function seedDatabase() {
  await db.execute(sql`DELETE FROM ${vipPackages}`);
  await db.insert(vipPackages).values([
    {
      name: "Stajyor",
      price: "0",
      dailyTasks: 3,
      perVideoReward: "0.31",
      dailyEarning: "0.95",
      level: 0,
      durationDays: 3,
      isLocked: false,
      emoji: "\u{1F193}",
      description: "Boshlang'ich sinov davri",
    },
    {
      name: "M1",
      price: "27",
      dailyTasks: 5,
      perVideoReward: "0.20",
      dailyEarning: "1.00",
      level: 1,
      durationDays: 60,
      isLocked: false,
      emoji: "\u{1F949}",
      description: "Kuniga 5 ta video vazifa",
    },
    {
      name: "M2",
      price: "63",
      dailyTasks: 6,
      perVideoReward: "0.42",
      dailyEarning: "2.50",
      level: 2,
      durationDays: 60,
      isLocked: false,
      emoji: "\u{1F948}",
      description: "Kuniga 6 ta video vazifa",
    },
    {
      name: "M3",
      price: "147",
      dailyTasks: 10,
      perVideoReward: "0.60",
      dailyEarning: "6.00",
      level: 3,
      durationDays: 60,
      isLocked: false,
      emoji: "\u{1F947}",
      description: "Kuniga 10 ta video vazifa",
    },
    {
      name: "M4",
      price: "343",
      dailyTasks: 14,
      perVideoReward: "1.05",
      dailyEarning: "14.70",
      level: 4,
      durationDays: 60,
      isLocked: true,
      emoji: "\u{1F512}",
      description: "Kuniga 14 ta video vazifa",
    },
    {
      name: "M5",
      price: "800",
      dailyTasks: 18,
      perVideoReward: "2.00",
      dailyEarning: "36.00",
      level: 5,
      durationDays: 60,
      isLocked: true,
      emoji: "\u{1F512}",
      description: "Kuniga 18 ta video vazifa",
    },
    {
      name: "M6",
      price: "1860",
      dailyTasks: 20,
      perVideoReward: "4.30",
      dailyEarning: "86.00",
      level: 6,
      durationDays: 60,
      isLocked: true,
      emoji: "\u{1F512}",
      description: "Kuniga 20 ta video vazifa",
    },
    {
      name: "M7",
      price: "4350",
      dailyTasks: 25,
      perVideoReward: "8.20",
      dailyEarning: "205.00",
      level: 7,
      durationDays: 60,
      isLocked: true,
      emoji: "\u{1F512}",
      description: "Kuniga 25 ta video vazifa",
    },
    {
      name: "M8",
      price: "10150",
      dailyTasks: 30,
      perVideoReward: "16.00",
      dailyEarning: "480.00",
      level: 8,
      durationDays: 60,
      isLocked: true,
      emoji: "\u{1F512}",
      description: "Kuniga 30 ta video vazifa",
    },
    {
      name: "M9",
      price: "23500",
      dailyTasks: 40,
      perVideoReward: "28.00",
      dailyEarning: "1120.00",
      level: 9,
      durationDays: 60,
      isLocked: true,
      emoji: "\u{1F512}",
      description: "Kuniga 40 ta video vazifa",
    },
    {
      name: "M10",
      price: "55000",
      dailyTasks: 50,
      perVideoReward: "53.00",
      dailyEarning: "2650.00",
      level: 10,
      durationDays: 60,
      isLocked: true,
      emoji: "\u{1F451}",
      description: "Kuniga 50 ta video vazifa",
    },
  ]);
  console.log("VIP packages seeded (11 tiers)");

  await db.execute(sql`DELETE FROM ${videos}`);
  {
    await db.insert(videos).values([
      {
        title: "Squid Game: Season 2",
        thumbnail: "https://img.youtube.com/vi/Ed1sGgHUo88/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=Ed1sGgHUo88",
        actors: "Lee Jung-jae, Wi Ha-jun, Gong Yoo",
        rating: "4.9",
        releaseDate: "2025-12-26",
        country: "Janubiy Koreya",
        duration: 25,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "The Last of Us: Season 2",
        thumbnail: "https://img.youtube.com/vi/_zHPsmXCjB0/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=_zHPsmXCjB0",
        actors: "Pedro Pascal, Bella Ramsey",
        rating: "4.8",
        releaseDate: "2026-04-13",
        country: "AQSH",
        duration: 22,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "Wednesday: Season 2",
        thumbnail: "https://img.youtube.com/vi/ueCc-AYUMRs/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=ueCc-AYUMRs",
        actors: "Jenna Ortega, Catherine Zeta-Jones",
        rating: "4.7",
        releaseDate: "2026-08-06",
        country: "AQSH",
        duration: 28,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "Stranger Things: Final Season",
        thumbnail: "https://img.youtube.com/vi/XwQRkOK5KC4/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=XwQRkOK5KC4",
        actors: "Millie Bobby Brown, Finn Wolfhard",
        rating: "4.8",
        releaseDate: "2025-11-27",
        country: "AQSH",
        duration: 30,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "House of the Dragon: Season 2",
        thumbnail: "https://img.youtube.com/vi/YN2H_sKcmGw/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=YN2H_sKcmGw",
        actors: "Matt Smith, Emma D'Arcy",
        rating: "4.7",
        releaseDate: "2024-06-16",
        country: "AQSH",
        duration: 25,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "Money Heist: Berlin",
        thumbnail: "https://img.youtube.com/vi/u3V5KDHRQvk/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=u3V5KDHRQvk",
        actors: "Pedro Alonso, Michelle Jenner",
        rating: "4.3",
        releaseDate: "2023-12-29",
        country: "Ispaniya",
        duration: 20,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "The Penguin",
        thumbnail: "https://img.youtube.com/vi/gn5QmllRCn4/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=gn5QmllRCn4",
        actors: "Colin Farrell, Cristin Milioti",
        rating: "4.6",
        releaseDate: "2024-09-19",
        country: "AQSH",
        duration: 22,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "Shōgun",
        thumbnail: "https://img.youtube.com/vi/C5pHpQqhmR4/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=C5pHpQqhmR4",
        actors: "Hiroyuki Sanada, Cosmo Jarvis, Anna Sawai",
        rating: "4.9",
        releaseDate: "2024-02-27",
        country: "Yaponiya",
        duration: 26,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "Fallout",
        thumbnail: "https://img.youtube.com/vi/TcMBFSGVi1c/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
        actors: "Ella Purnell, Walton Goggins, Aaron Moten",
        rating: "4.7",
        releaseDate: "2024-04-10",
        country: "AQSH",
        duration: 24,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "3 Body Problem",
        thumbnail: "https://img.youtube.com/vi/PLLQK9la6Go/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=PLLQK9la6Go",
        actors: "Jovan Adepo, John Bradley, Rosalind Chao",
        rating: "4.4",
        releaseDate: "2024-03-21",
        country: "AQSH",
        duration: 28,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "The Bear: Season 3",
        thumbnail: "https://img.youtube.com/vi/pBk4NYhWNMM/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=pBk4NYhWNMM",
        actors: "Jeremy Allen White, Ayo Edebiri, Ebon Moss-Bachrach",
        rating: "4.6",
        releaseDate: "2024-06-27",
        country: "AQSH",
        duration: 20,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "Arcane: Season 2",
        thumbnail: "https://img.youtube.com/vi/L0MK7qz13bU/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=L0MK7qz13bU",
        actors: "Hailee Steinfeld, Ella Purnell, Katie Leung",
        rating: "4.9",
        releaseDate: "2024-11-09",
        country: "AQSH",
        duration: 23,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "Reacher: Season 3",
        thumbnail: "https://img.youtube.com/vi/ue80QwXMRHg/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=ue80QwXMRHg",
        actors: "Alan Ritchson, Maria Sten",
        rating: "4.5",
        releaseDate: "2025-02-20",
        country: "AQSH",
        duration: 22,
        reward: "0",
        category: "Tele-shou",
      },
      {
        title: "Thunderbolts*",
        thumbnail: "https://img.youtube.com/vi/-sAOWhvheK8/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=-sAOWhvheK8",
        actors: "Florence Pugh, Sebastian Stan",
        rating: "4.6",
        releaseDate: "2025-05-02",
        country: "AQSH",
        duration: 24,
        reward: "0",
        category: "Treyler",
      },
      {
        title: "Mission Impossible: Final Reckoning",
        thumbnail: "https://img.youtube.com/vi/fsQgc9pCyDU/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=fsQgc9pCyDU",
        actors: "Tom Cruise, Hayley Atwell",
        rating: "4.9",
        releaseDate: "2025-05-23",
        country: "AQSH",
        duration: 26,
        reward: "0",
        category: "Treyler",
      },
      {
        title: "Avatar 3: Fire and Ash",
        thumbnail: "https://img.youtube.com/vi/xxEt9fnILgQ/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=xxEt9fnILgQ",
        actors: "Sam Worthington, Zoe Saldana",
        rating: "4.8",
        releaseDate: "2025-12-19",
        country: "AQSH",
        duration: 28,
        reward: "0",
        category: "Treyler",
      },
      {
        title: "Dune: Part Two",
        thumbnail: "https://img.youtube.com/vi/8g18jFHCLXk/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=8g18jFHCLXk",
        actors: "Timothée Chalamet, Zendaya, Austin Butler",
        rating: "4.8",
        releaseDate: "2024-03-01",
        country: "AQSH",
        duration: 25,
        reward: "0",
        category: "Treyler",
      },
      {
        title: "Deadpool & Wolverine",
        thumbnail: "https://img.youtube.com/vi/cqGjhVJWtEg/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=cqGjhVJWtEg",
        actors: "Ryan Reynolds, Hugh Jackman",
        rating: "4.7",
        releaseDate: "2024-07-26",
        country: "AQSH",
        duration: 23,
        reward: "0",
        category: "Treyler",
      },
      {
        title: "Gladiator II",
        thumbnail: "https://img.youtube.com/vi/KK8FHdFluOQ/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=KK8FHdFluOQ",
        actors: "Paul Mescal, Pedro Pascal, Denzel Washington",
        rating: "4.6",
        releaseDate: "2024-11-22",
        country: "AQSH",
        duration: 27,
        reward: "0",
        category: "Treyler",
      },
      {
        title: "Wicked",
        thumbnail: "https://img.youtube.com/vi/6COmYeLsz4c/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=6COmYeLsz4c",
        actors: "Ariana Grande, Cynthia Erivo",
        rating: "4.7",
        releaseDate: "2024-11-22",
        country: "AQSH",
        duration: 26,
        reward: "0",
        category: "Treyler",
      },
      {
        title: "Joker: Folie à Deux",
        thumbnail: "https://img.youtube.com/vi/mqqft2x_Aa4/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=mqqft2x_Aa4",
        actors: "Joaquin Phoenix, Lady Gaga",
        rating: "4.3",
        releaseDate: "2024-10-04",
        country: "AQSH",
        duration: 24,
        reward: "0",
        category: "Treyler",
      },
      {
        title: "Godzilla x Kong: The New Empire",
        thumbnail: "https://img.youtube.com/vi/Rt_UqUm38BI/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=Rt_UqUm38BI",
        actors: "Rebecca Hall, Brian Tyree Henry",
        rating: "4.4",
        releaseDate: "2024-03-29",
        country: "AQSH",
        duration: 22,
        reward: "0",
        category: "Treyler",
      },
      {
        title: "Venom: The Last Dance",
        thumbnail: "https://img.youtube.com/vi/YoHD9XEInc0/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=YoHD9XEInc0",
        actors: "Tom Hardy, Chiwetel Ejiofor",
        rating: "4.2",
        releaseDate: "2024-10-25",
        country: "AQSH",
        duration: 21,
        reward: "0",
        category: "Treyler",
      },
      {
        title: "Inside Out 2",
        thumbnail: "https://img.youtube.com/vi/d9MyW72ELq0/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=d9MyW72ELq0",
        actors: "Amy Poehler, Maya Hawke",
        rating: "4.8",
        releaseDate: "2024-06-14",
        country: "AQSH",
        duration: 20,
        reward: "0",
        category: "Treyler",
      },
      {
        title: "The Wild Robot",
        thumbnail: "https://img.youtube.com/vi/giXco2jaZ_4/maxresdefault.jpg",
        videoUrl: "https://www.youtube.com/watch?v=giXco2jaZ_4",
        actors: "Lupita Nyong'o, Pedro Pascal, Kit Connor",
        rating: "4.9",
        releaseDate: "2024-09-27",
        country: "AQSH",
        duration: 22,
        reward: "0",
        category: "Treyler",
      },
    ]);
    console.log("Videos seeded (13 TV shows + 12 trailers with verified YouTube URLs)");
  }

  const existingPlans = await db.select().from(fundPlans);
  const planDefs = [
    { name: "F1", lockDays: 13, dailyRoi: "2.30", minDeposit: "10", maxDeposit: "54", returnPrincipal: true },
    { name: "F2", lockDays: 27, dailyRoi: "2.60", minDeposit: "55", maxDeposit: "249", returnPrincipal: true },
    { name: "F3", lockDays: 45, dailyRoi: "3.00", minDeposit: "250", maxDeposit: "999", returnPrincipal: true },
    { name: "F4", lockDays: null, dailyRoi: "4.00", minDeposit: "1000", maxDeposit: null, returnPrincipal: false },
  ];
  for (const def of planDefs) {
    const exists = existingPlans.find(p => p.name === def.name);
    if (!exists) {
      await db.insert(fundPlans).values(def);
    } else {
      await db.update(fundPlans)
        .set({ lockDays: def.lockDays, dailyRoi: def.dailyRoi, minDeposit: def.minDeposit, maxDeposit: def.maxDeposit, returnPrincipal: def.returnPrincipal })
        .where(eq(fundPlans.id, exists.id));
    }
  }
  console.log("Fund plans seeded (4 F-Series) - IDs preserved");
}
